server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway: # 通过配置进行转发
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #          uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service # lb://+serviceName ,lb是uri协议，表示启动Gateway的负载均衡功能。
          predicates:
            - Path=/payment/get/**         # 断言，路径相匹配的进行路由
            - After=2022-06-29T15:40:03.685+08:00[Asia/Shanghai] # 在时间之后
            - Cookie=username, zzyy
            - Header=X-Request-Id, \d+  # 请求头要有X-Request-Id属性并且值为整数的正则表达式

        - id: payment_routh2
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**         # 断言，路径相匹配的进行路由


eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka